app:
  name: "top-gun-app-services"
  env: "development"
  port:
    http: 8080
    https: 8443
  path:
    cert: "./internal/assets/dev/tls/zercle-dev.crt"
    priv: "./internal/assets/dev/tls/zercle-dev.key"
    ca: "./internal/assets/dev/tls/rootCA.crt"
    log: "./log"

db:
  mariadb:
    sock: "/var/run/mysqld/mysqld.sock"
    host: "localhost"
    port: 3306
    username: ""
    password: ""
    db_name: ""
    conn:
      min: 1
      max: 2
  postgres:
    sock: "/var/run/postgresql"
    host: "185.84.161.188"
    port: 5432
    username: "postgres"
    password: "topgun-kkucoe"
    db_name: "postgres"
    conn:
      min: 1
      max: 2
  sqlite:
    db_name: "file:project.db"
  redis:
    host: "localhost"
    port: 6379
    username: ""
    password: ""
    db_name: 0
jwt:
  # openssl ecparam -name prime256v1 -genkey -noout -out privkey.pem
  private: "./internal/assets/dev/jwt/privkey.pem"
  # openssl ec -in privkey.pem -pubout -out pubkey.pem
  public: "./internal/assets/dev/jwt/pubkey.pem"
minio:
  endpoint: ""
  access_key: ""
  secret_key: ""
mqtt:
  broker: "ws://185.84.161.188:9001/mqtt"
  client_id: "mqttx_be33d6c6"
  username: "changerzaryx"
  password: "cn16022547"
workshop:
  ws: "ws://technest.ddns.net:8001/ws"
  key: "6807e4259a8a69f3f352cfc2fae2117f"